language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run test:coverage
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: https://github.com/KonstantinVVictoria/G_State.git
  local_dir: build
  on:
    branch: master
